/*******************************************************
*      File Message Area
*
* File name:   		tskScheduler.h
* Description:		this file is a header file of tskScheduler.c
* Create date: 		09-03-20
* Author:				  Shen KK
* Modify record:
*
*******************************************************/
#ifndef  	_TSK_SCHEDULER_H_
#define		_TSK_SCHEDULER_H_



void task0fun(void);

#ifndef _ONE_TASK_ONLY_T1_

void cyclictask_sys(void);

void task1fun_nor(void);
void task2fun_nor(void);
void task3fun_nor(void);
void task4fun_nor(void);
void task5fun_nor(void);
void task6fun_nor(void);
#if 0
void taskIntFun_I1(void);
void taskIntFun_I2(void);
void taskIntFun_I3(void);
void taskIntFun_I4(void);
void taskIntFun_I5(void);
void taskIntFun_I6(void);
void taskIntFun_I7(void);
void taskIntFun_I8(void);
#endif
#else

/*void task1fun_sys_nor(void);*/
void task1fun_nor(void); /* used the old name, so that configuration can be unchanged */

#endif

void progStop(void);
void taskinitfun(void);
void taskScheduleInitInterrupts(void);
void taskScheduleInitTimer(float interval);

void plcComm(void);

typedef enum
{
	kInitMode = 0,
	kSystemMode = 1,
	kNormalMode = 2,

	kFastImport = 3,
	kConsistentImport = 4,
	kConsistentExport = 5,
	kFastExport = 6

} tFBModes;

#define NUM_MODES 7

typedef enum
{
	kI1Task = 0,
	kI2Task = 1,
	kI3Task = 2,
	kI4Task = 3,
	kI5Task = 4,
	kI6Task = 5,
	kI7Task = 6,
	kI8Task = 7,
	kT1Task = 8,
	kT2Task = 9,
	kT3Task = 10,
	kT4Task = 11,
	kT5Task = 12

} tSystemTasks;

#ifndef _ONE_TASK_ONLY_T1_
#define NUM_TASKS 13
#else
#define NUM_TASKS 1
#endif

/*--------------------------------------------------------------------------- */
/* definitions used for task start and scheduling                             */
/*--------------------------------------------------------------------------- */

/* the following definitions are used to define code offsets for the different tasks and modes */
#define SIZEOF_COMPATIBILITY_KEY        5
#define SIZEOF_LD_INSTRUCTION           1
#define SIZEOF_JMP_OPCODE               1
#define SIZEOF_JMP_INSTRUCTION          3
#define SIZEOF_COMPATIBILITY_KEY_NC     8
#define SIZEOF_JMP_INSTRUCTION_NC       4
#define ALTTASKSCHEME_COMPATIBILITY_KEY 0x117B8A5F

#define I1I_OFFSET (SIZEOF_COMPATIBILITY_KEY)
#define I1I_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC)
#define I1S_OFFSET (SIZEOF_COMPATIBILITY_KEY + 1 * SIZEOF_JMP_INSTRUCTION)
#define I1S_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 1 * SIZEOF_JMP_INSTRUCTION_NC)
#define I1FI_OFFSET (SIZEOF_COMPATIBILITY_KEY + 2 * SIZEOF_JMP_INSTRUCTION)
#define I1FI_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 2 * SIZEOF_JMP_INSTRUCTION_NC)
#define I1N_OFFSET (SIZEOF_COMPATIBILITY_KEY + 3 * SIZEOF_JMP_INSTRUCTION)
#define I1N_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 3 * SIZEOF_JMP_INSTRUCTION_NC)
#define I1FE_OFFSET (SIZEOF_COMPATIBILITY_KEY + 4 * SIZEOF_JMP_INSTRUCTION)
#define I1FE_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 4 * SIZEOF_JMP_INSTRUCTION_NC)

#define I2I_OFFSET (SIZEOF_COMPATIBILITY_KEY + 5 * SIZEOF_JMP_INSTRUCTION)
#define I2I_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 5 * SIZEOF_JMP_INSTRUCTION_NC)
#define I2S_OFFSET (SIZEOF_COMPATIBILITY_KEY + 6 * SIZEOF_JMP_INSTRUCTION)
#define I2S_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 6 * SIZEOF_JMP_INSTRUCTION_NC)
#define I2FI_OFFSET (SIZEOF_COMPATIBILITY_KEY + 7 * SIZEOF_JMP_INSTRUCTION)
#define I2FI_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 7 * SIZEOF_JMP_INSTRUCTION_NC)
#define I2N_OFFSET (SIZEOF_COMPATIBILITY_KEY + 8 * SIZEOF_JMP_INSTRUCTION)
#define I2N_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 8 * SIZEOF_JMP_INSTRUCTION_NC)
#define I2FE_OFFSET (SIZEOF_COMPATIBILITY_KEY + 9 * SIZEOF_JMP_INSTRUCTION)
#define I2FE_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 9 * SIZEOF_JMP_INSTRUCTION_NC)

#define I3I_OFFSET (SIZEOF_COMPATIBILITY_KEY + 10 * SIZEOF_JMP_INSTRUCTION)
#define I3I_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 10 * SIZEOF_JMP_INSTRUCTION_NC)
#define I3S_OFFSET (SIZEOF_COMPATIBILITY_KEY + 11 * SIZEOF_JMP_INSTRUCTION)
#define I3S_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 11 * SIZEOF_JMP_INSTRUCTION_NC)
#define I3FI_OFFSET (SIZEOF_COMPATIBILITY_KEY + 12 * SIZEOF_JMP_INSTRUCTION)
#define I3FI_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 12 * SIZEOF_JMP_INSTRUCTION_NC)
#define I3N_OFFSET (SIZEOF_COMPATIBILITY_KEY + 13 * SIZEOF_JMP_INSTRUCTION)
#define I3N_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 13 * SIZEOF_JMP_INSTRUCTION_NC)
#define I3FE_OFFSET (SIZEOF_COMPATIBILITY_KEY + 14 * SIZEOF_JMP_INSTRUCTION)
#define I3FE_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 14 * SIZEOF_JMP_INSTRUCTION_NC)

#define I4I_OFFSET (SIZEOF_COMPATIBILITY_KEY + 15 * SIZEOF_JMP_INSTRUCTION)
#define I4I_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 15 * SIZEOF_JMP_INSTRUCTION_NC)
#define I4S_OFFSET (SIZEOF_COMPATIBILITY_KEY + 16 * SIZEOF_JMP_INSTRUCTION)
#define I4S_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 16 * SIZEOF_JMP_INSTRUCTION_NC)
#define I4FI_OFFSET (SIZEOF_COMPATIBILITY_KEY + 17 * SIZEOF_JMP_INSTRUCTION)
#define I4FI_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 17 * SIZEOF_JMP_INSTRUCTION_NC)
#define I4N_OFFSET (SIZEOF_COMPATIBILITY_KEY + 18 * SIZEOF_JMP_INSTRUCTION)
#define I4N_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 18 * SIZEOF_JMP_INSTRUCTION_NC)
#define I4FE_OFFSET (SIZEOF_COMPATIBILITY_KEY + 19 * SIZEOF_JMP_INSTRUCTION)
#define I4FE_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 19 * SIZEOF_JMP_INSTRUCTION_NC)

#define I5I_OFFSET (SIZEOF_COMPATIBILITY_KEY + 20 * SIZEOF_JMP_INSTRUCTION)
#define I5I_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 20 * SIZEOF_JMP_INSTRUCTION_NC)
#define I5S_OFFSET (SIZEOF_COMPATIBILITY_KEY + 21 * SIZEOF_JMP_INSTRUCTION)
#define I5S_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 21 * SIZEOF_JMP_INSTRUCTION_NC)
#define I5FI_OFFSET (SIZEOF_COMPATIBILITY_KEY + 22 * SIZEOF_JMP_INSTRUCTION)
#define I5FI_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 22 * SIZEOF_JMP_INSTRUCTION_NC)
#define I5N_OFFSET (SIZEOF_COMPATIBILITY_KEY + 23 * SIZEOF_JMP_INSTRUCTION)
#define I5N_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 23 * SIZEOF_JMP_INSTRUCTION_NC)
#define I5FE_OFFSET (SIZEOF_COMPATIBILITY_KEY + 24 * SIZEOF_JMP_INSTRUCTION)
#define I5FE_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 24 * SIZEOF_JMP_INSTRUCTION_NC)

#define I6I_OFFSET (SIZEOF_COMPATIBILITY_KEY + 25 * SIZEOF_JMP_INSTRUCTION)
#define I6I_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 25 * SIZEOF_JMP_INSTRUCTION_NC)
#define I6S_OFFSET (SIZEOF_COMPATIBILITY_KEY + 26 * SIZEOF_JMP_INSTRUCTION)
#define I6S_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 26 * SIZEOF_JMP_INSTRUCTION_NC)
#define I6FI_OFFSET (SIZEOF_COMPATIBILITY_KEY + 27 * SIZEOF_JMP_INSTRUCTION)
#define I6FI_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 27 * SIZEOF_JMP_INSTRUCTION_NC)
#define I6N_OFFSET (SIZEOF_COMPATIBILITY_KEY + 28 * SIZEOF_JMP_INSTRUCTION)
#define I6N_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 28 * SIZEOF_JMP_INSTRUCTION_NC)
#define I6FE_OFFSET (SIZEOF_COMPATIBILITY_KEY + 29 * SIZEOF_JMP_INSTRUCTION)
#define I6FE_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 29 * SIZEOF_JMP_INSTRUCTION_NC)

#define I7I_OFFSET (SIZEOF_COMPATIBILITY_KEY + 30 * SIZEOF_JMP_INSTRUCTION)
#define I7I_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 30 * SIZEOF_JMP_INSTRUCTION_NC)
#define I7S_OFFSET (SIZEOF_COMPATIBILITY_KEY + 31 * SIZEOF_JMP_INSTRUCTION)
#define I7S_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 31 * SIZEOF_JMP_INSTRUCTION_NC)
#define I7FI_OFFSET (SIZEOF_COMPATIBILITY_KEY + 32 * SIZEOF_JMP_INSTRUCTION)
#define I7FI_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 32 * SIZEOF_JMP_INSTRUCTION_NC)
#define I7N_OFFSET (SIZEOF_COMPATIBILITY_KEY + 33 * SIZEOF_JMP_INSTRUCTION)
#define I7N_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 33 * SIZEOF_JMP_INSTRUCTION_NC)
#define I7FE_OFFSET (SIZEOF_COMPATIBILITY_KEY + 34 * SIZEOF_JMP_INSTRUCTION)
#define I7FE_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 34 * SIZEOF_JMP_INSTRUCTION_NC)

#define I8I_OFFSET (SIZEOF_COMPATIBILITY_KEY + 35 * SIZEOF_JMP_INSTRUCTION)
#define I8I_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 35 * SIZEOF_JMP_INSTRUCTION_NC)
#define I8S_OFFSET (SIZEOF_COMPATIBILITY_KEY + 36 * SIZEOF_JMP_INSTRUCTION)
#define I8S_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 36 * SIZEOF_JMP_INSTRUCTION_NC)
#define I8FI_OFFSET (SIZEOF_COMPATIBILITY_KEY + 37 * SIZEOF_JMP_INSTRUCTION)
#define I8FI_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 37 * SIZEOF_JMP_INSTRUCTION_NC)
#define I8N_OFFSET (SIZEOF_COMPATIBILITY_KEY + 38 * SIZEOF_JMP_INSTRUCTION)
#define I8N_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 38 * SIZEOF_JMP_INSTRUCTION_NC)
#define I8FE_OFFSET (SIZEOF_COMPATIBILITY_KEY + 39 * SIZEOF_JMP_INSTRUCTION)
#define I8FE_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 39 * SIZEOF_JMP_INSTRUCTION_NC)

#define T1I_OFFSET (SIZEOF_COMPATIBILITY_KEY + 40 * SIZEOF_JMP_INSTRUCTION)
#define T1I_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 40 * SIZEOF_JMP_INSTRUCTION_NC)
#define T1S_OFFSET (SIZEOF_COMPATIBILITY_KEY + 41 * SIZEOF_JMP_INSTRUCTION)
#define T1S_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 41 * SIZEOF_JMP_INSTRUCTION_NC)
#define T1FI_OFFSET (SIZEOF_COMPATIBILITY_KEY + 42 * SIZEOF_JMP_INSTRUCTION)
#define T1FI_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 42 * SIZEOF_JMP_INSTRUCTION_NC)
#define T1CI_OFFSET (SIZEOF_COMPATIBILITY_KEY + 43 * SIZEOF_JMP_INSTRUCTION)
#define T1CI_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 43 * SIZEOF_JMP_INSTRUCTION_NC)
#define T1N_OFFSET (SIZEOF_COMPATIBILITY_KEY + 44 * SIZEOF_JMP_INSTRUCTION)
#define T1N_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 44 * SIZEOF_JMP_INSTRUCTION_NC)
#define T1CE_OFFSET (SIZEOF_COMPATIBILITY_KEY + 45 * SIZEOF_JMP_INSTRUCTION)
#define T1CE_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 45 * SIZEOF_JMP_INSTRUCTION_NC)
#define T1FE_OFFSET (SIZEOF_COMPATIBILITY_KEY + 46 * SIZEOF_JMP_INSTRUCTION)
#define T1FE_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 46 * SIZEOF_JMP_INSTRUCTION_NC)

#define T2I_OFFSET (SIZEOF_COMPATIBILITY_KEY + 47 * SIZEOF_JMP_INSTRUCTION)
#define T2I_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 47 * SIZEOF_JMP_INSTRUCTION_NC)
#define T2S_OFFSET (SIZEOF_COMPATIBILITY_KEY + 48 * SIZEOF_JMP_INSTRUCTION)
#define T2S_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 48 * SIZEOF_JMP_INSTRUCTION_NC)
#define T2FI_OFFSET (SIZEOF_COMPATIBILITY_KEY + 49 * SIZEOF_JMP_INSTRUCTION)
#define T2FI_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 49 * SIZEOF_JMP_INSTRUCTION_NC)
#define T2CI_OFFSET (SIZEOF_COMPATIBILITY_KEY + 50 * SIZEOF_JMP_INSTRUCTION)
#define T2CI_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 50 * SIZEOF_JMP_INSTRUCTION_NC)
#define T2N_OFFSET (SIZEOF_COMPATIBILITY_KEY + 51 * SIZEOF_JMP_INSTRUCTION)
#define T2N_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 51 * SIZEOF_JMP_INSTRUCTION_NC)
#define T2CE_OFFSET (SIZEOF_COMPATIBILITY_KEY + 52 * SIZEOF_JMP_INSTRUCTION)
#define T2CE_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 52 * SIZEOF_JMP_INSTRUCTION_NC)
#define T2FE_OFFSET (SIZEOF_COMPATIBILITY_KEY + 53 * SIZEOF_JMP_INSTRUCTION)
#define T2FE_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 53 * SIZEOF_JMP_INSTRUCTION_NC)

#define T3I_OFFSET (SIZEOF_COMPATIBILITY_KEY + 54 * SIZEOF_JMP_INSTRUCTION)
#define T3I_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 54 * SIZEOF_JMP_INSTRUCTION_NC)
#define T3S_OFFSET (SIZEOF_COMPATIBILITY_KEY + 55 * SIZEOF_JMP_INSTRUCTION)
#define T3S_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 55 * SIZEOF_JMP_INSTRUCTION_NC)
#define T3FI_OFFSET (SIZEOF_COMPATIBILITY_KEY + 56 * SIZEOF_JMP_INSTRUCTION)
#define T3FI_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 56 * SIZEOF_JMP_INSTRUCTION_NC)
#define T3CI_OFFSET (SIZEOF_COMPATIBILITY_KEY + 57 * SIZEOF_JMP_INSTRUCTION)
#define T3CI_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 57 * SIZEOF_JMP_INSTRUCTION_NC)
#define T3N_OFFSET (SIZEOF_COMPATIBILITY_KEY + 58 * SIZEOF_JMP_INSTRUCTION)
#define T3N_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 58 * SIZEOF_JMP_INSTRUCTION_NC)
#define T3CE_OFFSET (SIZEOF_COMPATIBILITY_KEY + 59 * SIZEOF_JMP_INSTRUCTION)
#define T3CE_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 59 * SIZEOF_JMP_INSTRUCTION_NC)
#define T3FE_OFFSET (SIZEOF_COMPATIBILITY_KEY + 60 * SIZEOF_JMP_INSTRUCTION)
#define T3FE_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 60 * SIZEOF_JMP_INSTRUCTION_NC)

#define T4I_OFFSET (SIZEOF_COMPATIBILITY_KEY + 61 * SIZEOF_JMP_INSTRUCTION)
#define T4I_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 61 * SIZEOF_JMP_INSTRUCTION_NC)
#define T4S_OFFSET (SIZEOF_COMPATIBILITY_KEY + 62 * SIZEOF_JMP_INSTRUCTION)
#define T4S_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 62 * SIZEOF_JMP_INSTRUCTION_NC)
#define T4FI_OFFSET (SIZEOF_COMPATIBILITY_KEY + 63 * SIZEOF_JMP_INSTRUCTION)
#define T4FI_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 63 * SIZEOF_JMP_INSTRUCTION_NC)
#define T4CI_OFFSET (SIZEOF_COMPATIBILITY_KEY + 64 * SIZEOF_JMP_INSTRUCTION)
#define T4CI_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 64 * SIZEOF_JMP_INSTRUCTION_NC)
#define T4N_OFFSET (SIZEOF_COMPATIBILITY_KEY + 65 * SIZEOF_JMP_INSTRUCTION)
#define T4N_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 65 * SIZEOF_JMP_INSTRUCTION_NC)
#define T4CE_OFFSET (SIZEOF_COMPATIBILITY_KEY + 66 * SIZEOF_JMP_INSTRUCTION)
#define T4CE_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 66 * SIZEOF_JMP_INSTRUCTION_NC)
#define T4FE_OFFSET (SIZEOF_COMPATIBILITY_KEY + 67 * SIZEOF_JMP_INSTRUCTION)
#define T4FE_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 67 * SIZEOF_JMP_INSTRUCTION_NC)

#define T5I_OFFSET (SIZEOF_COMPATIBILITY_KEY + 68 * SIZEOF_JMP_INSTRUCTION)
#define T5I_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 68 * SIZEOF_JMP_INSTRUCTION_NC)
#define T5S_OFFSET (SIZEOF_COMPATIBILITY_KEY + 69 * SIZEOF_JMP_INSTRUCTION)
#define T5S_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 69 * SIZEOF_JMP_INSTRUCTION_NC)
#define T5FI_OFFSET (SIZEOF_COMPATIBILITY_KEY + 70 * SIZEOF_JMP_INSTRUCTION)
#define T5FI_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 70 * SIZEOF_JMP_INSTRUCTION_NC)
#define T5CI_OFFSET (SIZEOF_COMPATIBILITY_KEY + 71 * SIZEOF_JMP_INSTRUCTION)
#define T5CI_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 71 * SIZEOF_JMP_INSTRUCTION_NC)
#define T5N_OFFSET (SIZEOF_COMPATIBILITY_KEY + 72 * SIZEOF_JMP_INSTRUCTION)
#define T5N_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 72 * SIZEOF_JMP_INSTRUCTION_NC)
#define T5CE_OFFSET (SIZEOF_COMPATIBILITY_KEY + 73 * SIZEOF_JMP_INSTRUCTION)
#define T5CE_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 73 * SIZEOF_JMP_INSTRUCTION_NC)
#define T5FE_OFFSET (SIZEOF_COMPATIBILITY_KEY + 74 * SIZEOF_JMP_INSTRUCTION)
#define T5FE_OFFSET_NC (SIZEOF_COMPATIBILITY_KEY_NC + 74 * SIZEOF_JMP_INSTRUCTION_NC)

/*--------------------------------------------------------------------------- */
/* definitions used for program lists                                         */
/*--------------------------------------------------------------------------- */
#define I1I_LIST pControlSetI1I->pProgramList
#define I1S_LIST pControlSetI1S->pProgramList
#define I1FI_LIST pControlSetI1FI->pProgramList
#define I1N_LIST pControlSetI1N->pProgramList
#define I1FE_LIST pControlSetI1FE->pProgramList
#define I2I_LIST pControlSetI2I->pProgramList
#define I2S_LIST pControlSetI2S->pProgramList
#define I2FI_LIST pControlSetI2FI->pProgramList
#define I2N_LIST pControlSetI2N->pProgramList
#define I2FE_LIST pControlSetI2FE->pProgramList
#define I3I_LIST pControlSetI3I->pProgramList
#define I3S_LIST pControlSetI3S->pProgramList
#define I3FI_LIST pControlSetI3FI->pProgramList
#define I3N_LIST pControlSetI3N->pProgramList
#define I3FE_LIST pControlSetI3FE->pProgramList
#define I4I_LIST pControlSetI4I->pProgramList
#define I4S_LIST pControlSetI4S->pProgramList
#define I4FI_LIST pControlSetI4FI->pProgramList
#define I4N_LIST pControlSetI4N->pProgramList
#define I4FE_LIST pControlSetI4FE->pProgramList
#define I5I_LIST pControlSetI5I->pProgramList
#define I5S_LIST pControlSetI5S->pProgramList
#define I5FI_LIST pControlSetI5FI->pProgramList
#define I5N_LIST pControlSetI5N->pProgramList
#define I5FE_LIST pControlSetI5FE->pProgramList
#define I6I_LIST pControlSetI6I->pProgramList
#define I6S_LIST pControlSetI6S->pProgramList
#define I6FI_LIST pControlSetI6FI->pProgramList
#define I6N_LIST pControlSetI6N->pProgramList
#define I6FE_LIST pControlSetI6FE->pProgramList
#define I7I_LIST pControlSetI7I->pProgramList
#define I7S_LIST pControlSetI7S->pProgramList
#define I7FI_LIST pControlSetI7FI->pProgramList
#define I7N_LIST pControlSetI7N->pProgramList
#define I7FE_LIST pControlSetI7FE->pProgramList
#define I8I_LIST pControlSetI8I->pProgramList
#define I8S_LIST pControlSetI8S->pProgramList
#define I8FI_LIST pControlSetI8FI->pProgramList
#define I8N_LIST pControlSetI8N->pProgramList
#define I8FE_LIST pControlSetI8FE->pProgramList
#define T1I_LIST pControlSetT1I->pProgramList
#define T1S_LIST pControlSetT1S->pProgramList
#define T1FI_LIST pControlSetT1FI->pProgramList
#define T1CI_LIST pControlSetT1CI->pProgramList
#define T1N_LIST pControlSetT1N->pProgramList
#define T1CE_LIST pControlSetT1CE->pProgramList
#define T1FE_LIST pControlSetT1FE->pProgramList
#define T2I_LIST pControlSetT2I->pProgramList
#define T2S_LIST pControlSetT2S->pProgramList
#define T2FI_LIST pControlSetT2FI->pProgramList
#define T2CI_LIST pControlSetT2CI->pProgramList
#define T2N_LIST pControlSetT2N->pProgramList
#define T2CE_LIST pControlSetT2CE->pProgramList
#define T2FE_LIST pControlSetT2FE->pProgramList
#define T3I_LIST pControlSetT3I->pProgramList
#define T3S_LIST pControlSetT3S->pProgramList
#define T3FI_LIST pControlSetT3FI->pProgramList
#define T3CI_LIST pControlSetT3CI->pProgramList
#define T3N_LIST pControlSetT3N->pProgramList
#define T3CE_LIST pControlSetT3CE->pProgramList
#define T3FE_LIST pControlSetT3FE->pProgramList
#define T4I_LIST pControlSetT4I->pProgramList
#define T4S_LIST pControlSetT4S->pProgramList
#define T4FI_LIST pControlSetT4FI->pProgramList
#define T4CI_LIST pControlSetT4CI->pProgramList
#define T4N_LIST pControlSetT4N->pProgramList
#define T4CE_LIST pControlSetT4CE->pProgramList
#define T4FE_LIST pControlSetT4FE->pProgramList
#define T5I_LIST pControlSetT5I->pProgramList
#define T5S_LIST pControlSetT5S->pProgramList
#define T5FI_LIST pControlSetT5FI->pProgramList
#define T5CI_LIST pControlSetT5CI->pProgramList
#define T5N_LIST pControlSetT5N->pProgramList
#define T5CE_LIST pControlSetT5CE->pProgramList
#define T5FE_LIST pControlSetT5FE->pProgramList

#endif
