/******************************************************************************
 *    (c) 2002 infoteam Software GmbH, D-91088 Bubenreuth, Tel. +49-9131-7800-0
 *    
 *    PROJEKT:        P431
 *    SWCI:            CBE
 *    DESCRIPTION:    
 *    
 *****************************************************************************/

#if !defined(AFX_IPDISTBL_H__71B277FD_5B3B_11D5_9CFF_009027715570__INCLUDED_)
#define AFX_IPDISTBL_H__71B277FD_5B3B_11D5_9CFF_009027715570__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif /* _MSC_VER > 1000*/

#define OP_SIZE                1
#define OP_SIZE_CONST_1        2
#define OP_SIZE_CONST_2        3
#define OP_SIZE_CONST_3        4
#define OP_SIZE_CONST_4        5
#define OP_SIZE_CONST_6        7
#define OP_SIZE_CONST_8        9
#define OP_SIZE_CONST_ANY    0
#define OP_NEAR_BYREF_SIZE  3
#define OP_FAR_SIZE         5
#define OP_PARBYTE_1        2
#define OP_PARBYTE_2        3
#define OP_PARBYTE_3        4
#define OP_PARBYTE_4        5
#define OP_PARBYTE_5        6


typedef struct
{
    BYTE m_bIpOpcLen;        /* OpCode-Length in Bytes*/
    char m_szIpOpcStr[39];   /* plain text*/
} tIpOpcodeStrTab;

static tIpOpcodeStrTab IpOpcodeStrTab[256] = {  
/*------------------------------------------------------------------------*/
/* NOP*/
/*------------------------------------------------------------------------*/
/*   0 */    { OP_SIZE,                "NOP"                    }, 
/*------------------------------------------------------------------------*/
/* program branch*/
/*------------------------------------------------------------------------*/
/*   1 */    { OP_NEAR_BYREF_SIZE,   "JMP"                    },              
/*   2 */   { OP_NEAR_BYREF_SIZE,   "JMPC"                    },              
/*   3 */   { OP_NEAR_BYREF_SIZE,   "JMPCN"                    },

/*   4 */   { OP_NEAR_BYREF_SIZE,   "CAL"                    },               
/*   5 */   { OP_NEAR_BYREF_SIZE,   "CALC"                    },           
/*   6 */   { OP_NEAR_BYREF_SIZE,   "CALCN"                    },             

/*   7 */   { OP_SIZE,                "RET"                    },                             
/*   8 */   { OP_SIZE,                "RETC"                    },                             
/*   9 */   { OP_SIZE,                "RETCN"                    },

/*------------------------------------------------------------------------*/
/* Variable access*/
/*------------------------------------------------------------------------*/
/*  10 */   { OP_NEAR_BYREF_SIZE,   "LD_NEAR_BIT"            },
/*  11 */   { OP_NEAR_BYREF_SIZE,   "LD_NEAR_1"                },
/*  12 */   { OP_NEAR_BYREF_SIZE,   "LD_NEAR_2"                }, 
/*  13 */   { OP_NEAR_BYREF_SIZE,   "LD_NEAR_4"                },
/*  14 */   { OP_NEAR_BYREF_SIZE,   "LD_NEAR_ANY"            },
/*  15 */   { OP_FAR_SIZE,            "LD_FAR_BIT"            },
/*  16 */   { OP_FAR_SIZE,            "LD_FAR_1"              },
/*  17 */   { OP_FAR_SIZE,            "LD_FAR_2"              },
/*  18 */   { OP_FAR_SIZE,            "LD_FAR_4"              },
/*  19 */   { OP_FAR_SIZE,            "LD_FAR_ANY"            },
/*  20 */   { OP_NEAR_BYREF_SIZE,   "LD_BYREF_BIT"          },
/*  21 */   { OP_NEAR_BYREF_SIZE,   "LD_BYREF_1"            },
/*  22 */   { OP_NEAR_BYREF_SIZE,   "LD_BYREF_2"            },
/*  23 */   { OP_NEAR_BYREF_SIZE,   "LD_BYREF_4"            },
/*  24 */   { OP_NEAR_BYREF_SIZE,   "LD_BYREF_ANY"          },
/*  25 */   { OP_SIZE,                "LD_IND_BIT"            },
/*  26 */   { OP_SIZE,                "LD_IND_1"                },
/*  27 */   { OP_SIZE,                "LD_IND_2"                },
/*  28 */   { OP_SIZE,                "LD_IND_4"                },
/*  29 */   { OP_SIZE,                "LD_IND_ANY"            },

/*  30 */   { OP_SIZE,                "LD_CONST_TRUE"         },
/*  31 */   { OP_SIZE,                "LD_CONST_FALSE"        },
/*  32 */   { OP_SIZE_CONST_1,        "LD_CONST_1"            },
/*  33 */   { OP_SIZE_CONST_2,        "LD_CONST_2"            },
/*  34 */   { OP_SIZE_CONST_4,        "LD_CONST_4"            },
/*  35 */   { OP_SIZE_CONST_ANY,    "LD_CONST_ANY"          },

/*  36 */   { OP_NEAR_BYREF_SIZE,   "LDN_NEAR_BIT"            },
/*  37 */   { OP_NEAR_BYREF_SIZE,   "LDN_NEAR_1"            },
/*  38 */   { OP_NEAR_BYREF_SIZE,   "LDN_NEAR_2"            },
/*  39 */   { OP_NEAR_BYREF_SIZE,   "LDN_NEAR_4"            },
/*  40 */   { OP_FAR_SIZE,            "LDN_FAR_BIT"           },
/*  41 */   { OP_FAR_SIZE,            "LDN_FAR_1"             },
/*  42 */   { OP_FAR_SIZE,            "LDN_FAR_2"             },
/*  43 */   { OP_FAR_SIZE,            "LDN_FAR_4"             },
/*  44 */   { OP_NEAR_BYREF_SIZE,   "LDN_BYREF_BIT"         },
/*  45 */   { OP_NEAR_BYREF_SIZE,   "LDN_BYREF_1"           },
/*  46 */   { OP_NEAR_BYREF_SIZE,   "LDN_BYREF_2"           },
/*  47 */   { OP_NEAR_BYREF_SIZE,   "LDN_BYREF_4"           },
/*  48 */   { OP_SIZE,                "LDN_IND_BIT"            },
/*  49 */   { OP_SIZE,                "LDN_IND_1"                },
/*  50 */   { OP_SIZE,                "LDN_IND_2"                },
/*  51 */   { OP_SIZE,                "LDN_IND_4"                },

/*  52 */   { OP_NEAR_BYREF_SIZE,   "ST_NEAR_BIT"           },
/*  53 */   { OP_NEAR_BYREF_SIZE,   "ST_NEAR_1"             },
/*  54 */   { OP_NEAR_BYREF_SIZE,   "ST_NEAR_2"             },
/*  55 */   { OP_NEAR_BYREF_SIZE,   "ST_NEAR_4"             },
/*  56 */   { OP_NEAR_BYREF_SIZE,   "ST_NEAR_ANY"           },
/*  57 */   { OP_FAR_SIZE,            "ST_FAR_BIT"            },
/*  58 */   { OP_FAR_SIZE,            "ST_FAR_1"              },
/*  59 */   { OP_FAR_SIZE,            "ST_FAR_2"              },
/*  60 */   { OP_FAR_SIZE,            "ST_FAR_4"              },
/*  61 */   { OP_FAR_SIZE,            "ST_FAR_ANY"            },
/*  62 */   { OP_NEAR_BYREF_SIZE,   "ST_BYREF_BIT"          },
/*  63 */   { OP_NEAR_BYREF_SIZE,   "ST_BYREF_1"            },
/*  64 */   { OP_NEAR_BYREF_SIZE,   "ST_BYREF_2"            },
/*  65 */   { OP_NEAR_BYREF_SIZE,   "ST_BYREF_4"            },
/*  66 */   { OP_NEAR_BYREF_SIZE,   "ST_BYREF_ANY"          },
/*  67 */   { OP_SIZE,                "ST_IND_BIT"            },
/*  68 */   { OP_SIZE,                "ST_IND_1"                },
/*  69 */   { OP_SIZE,                "ST_IND_2"                },
/*  70 */   { OP_SIZE,                "ST_IND_4"                },
/*  71 */   { OP_SIZE,                "ST_IND_ANY"            },

/*  72 */   { OP_NEAR_BYREF_SIZE,   "STN_NEAR_BIT"          },
/*  73 */   { OP_NEAR_BYREF_SIZE,   "STN_NEAR_1"            },
/*  74 */   { OP_NEAR_BYREF_SIZE,   "STN_NEAR_2"            },
/*  75 */   { OP_NEAR_BYREF_SIZE,   "STN_NEAR_4"            },
/*  76 */   { OP_FAR_SIZE,            "STN_FAR_BIT"           },
/*  77 */   { OP_FAR_SIZE,            "STN_FAR_1"             },
/*  78 */   { OP_FAR_SIZE,            "STN_FAR_2"             },
/*  79 */   { OP_FAR_SIZE,            "STN_FAR_4"             },
/*  80 */   { OP_NEAR_BYREF_SIZE,   "STN_BYREF_BIT"         },
/*  81 */   { OP_NEAR_BYREF_SIZE,   "STN_BYREF_1"           },
/*  82 */   { OP_NEAR_BYREF_SIZE,   "STN_BYREF_2"           },
/*  83 */   { OP_NEAR_BYREF_SIZE,   "STN_BYREF_4"           },
/*  84 */   { OP_SIZE,                "STN_IND_BIT"            },
/*  85 */   { OP_SIZE,                "STN_IND_1"                },
/*  86 */   { OP_SIZE,                "STN_IND_2"                },
/*  87 */   { OP_SIZE,                "STN_IND_4"                },      
      
/*  88 */   { OP_NEAR_BYREF_SIZE,   "S_NEAR_BIT"            },
/*  89 */   { OP_FAR_SIZE,            "S_FAR_BIT"             },
/*  90 */   { OP_NEAR_BYREF_SIZE,   "S_BYREF_BIT"           },
/*  91 */   { OP_SIZE,                "S_IND_BIT"                },
/*  92 */   { OP_NEAR_BYREF_SIZE,   "R_NEAR_BIT"            },
/*  93 */   { OP_FAR_SIZE,            "R_FAR_BIT"             },
/*  94 */   { OP_NEAR_BYREF_SIZE,   "R_BYREF_BIT"           },    
/*  95 */   { OP_SIZE,                "R_IND_BIT"                },

/*  96 */   { OP_NEAR_BYREF_SIZE,   "CREATE_REFERENCE"      },
/*  97 */   { OP_NEAR_BYREF_SIZE,   "LD_REFERENCE"          },
/*  98 */   { OP_FAR_SIZE,            "ST_REFERENCE"          },
/*  99 */   { OP_NEAR_BYREF_SIZE,    "ADD_OFFSET"            },
/* 100 */   { OP_SIZE,                "LD_INSTANCE_DATA"      },  
/* 101 */   { OP_SIZE,                "ST_INSTANCE_DATA"      },  

/* 102 */   { OP_NEAR_BYREF_SIZE,   "LDS_NEAR_BIT"          },
/* 103 */   { OP_NEAR_BYREF_SIZE,   "LDS_NEAR_1"            },
/* 104 */   { OP_NEAR_BYREF_SIZE,   "LDS_NEAR_2"            },
/* 105 */   { OP_NEAR_BYREF_SIZE,   "LDS_NEAR_4"            },
/* 106 */   { OP_NEAR_BYREF_SIZE,    "LDS_NEAR_ANY"            },
/* 107 */   { OP_FAR_SIZE,            "LDS_FAR_BIT"           },
/* 108 */   { OP_FAR_SIZE,            "LDS_FAR_1"             },
/* 109 */   { OP_FAR_SIZE,            "LDS_FAR_2"             },
/* 110 */   { OP_FAR_SIZE,            "LDS_FAR_4"             },
/* 111 */   { OP_FAR_SIZE,            "LDS_FAR_ANY"            },
/* 112 */   { OP_NEAR_BYREF_SIZE,   "LDS_BYREF_BIT"         },
/* 113 */   { OP_NEAR_BYREF_SIZE,   "LDS_BYREF_1"           },
/* 114 */   { OP_NEAR_BYREF_SIZE,   "LDS_BYREF_2"           },
/* 115 */   { OP_NEAR_BYREF_SIZE,   "LDS_BYREF_4"           },
/* 116 */   { OP_NEAR_BYREF_SIZE,    "LDS_BYREF_ANY"            },
/* 117 */   { OP_SIZE,                "LDS_IND_BIT"            },
/* 118 */   { OP_SIZE,                "LDS_IND_1"                },
/* 119 */   { OP_SIZE,                "LDS_IND_2"                },
/* 120 */   { OP_SIZE,                "LDS_IND_4"                },
/* 121 */   { OP_SIZE,                "LDS_IND_ANY"            },
   
/* 122 */   { OP_SIZE,                "LDS_CONST_TRUE"        },
/* 123 */   { OP_SIZE,                "LDS_CONST_FALSE"       },
/* 124 */   { OP_SIZE_CONST_1,        "LDS_CONST_1"           },
/* 125 */   { OP_SIZE_CONST_2,        "LDS_CONST_2"           },
/* 126 */   { OP_SIZE_CONST_4,        "LDS_CONST_4"           },
/* 127 */   { OP_SIZE_CONST_ANY,    "LDS_CONST_ANY"            },
   
/* 128 */   { OP_NEAR_BYREF_SIZE,   "LDNS_NEAR_BIT"         },
/* 129 */   { OP_NEAR_BYREF_SIZE,   "LDNS_NEAR_1"           },
/* 130 */   { OP_NEAR_BYREF_SIZE,   "LDNS_NEAR_2"           },
/* 131 */   { OP_NEAR_BYREF_SIZE,   "LDNS_NEAR_4"           },
/* 132 */   { OP_FAR_SIZE,            "LDNS_FAR_BIT"          },
/* 133 */   { OP_FAR_SIZE,            "LDNS_FAR_1"            },
/* 134 */   { OP_FAR_SIZE,            "LDNS_FAR_2"            },
/* 135 */   { OP_FAR_SIZE,            "LDNS_FAR_4"            },
/* 136 */   { OP_NEAR_BYREF_SIZE,   "LDNS_BYREF_BIT"        },
/* 137 */   { OP_NEAR_BYREF_SIZE,   "LDNS_BYREF_1"          },
/* 138 */   { OP_NEAR_BYREF_SIZE,   "LDNS_BYREF_2"          },
/* 139 */   { OP_NEAR_BYREF_SIZE,   "LDNS_BYREF_4"          },

/* 140 */   { OP_SIZE,                "LDNS_IND_BIT"            },
/* 141 */   { OP_SIZE,                "LDNS_IND_1"            },
/* 142 */   { OP_SIZE,                "LDNS_IND_2"            },
/* 143 */   { OP_SIZE,                "LDNS_IND_4"            },

/* 144 */   { OP_SIZE,                "PUSH_AE"                },
/* 145 */   { OP_SIZE,                "POP_AE"                },
/* 146 */   { OP_SIZE,                "PUSH_REF"                },
/* 147 */   { OP_SIZE,                "POP_REF"                },
/* 148 */   { OP_SIZE,                "PUSH_AE_ANY"            },
/* 149 */   { OP_SIZE,                "POP_AE_ANY"            },

/* 150 */   { OP_NEAR_BYREF_SIZE,   "RESTORE_DATA"          },

/*------------------------------------------------------------------------*/
/* operators*/
/*------------------------------------------------------------------------*/
/* 151 */   { OP_SIZE,                "AND_BIT"               },
/* 152 */   { OP_SIZE,                "AND_1"                 },
/* 153 */   { OP_SIZE,                "AND_2"                 },
/* 154 */   { OP_SIZE,                "AND_4"                 },

/* 155 */   { OP_SIZE,                "OR_BIT"                },
/* 156 */   { OP_SIZE,                "OR_1"                  },
/* 157 */   { OP_SIZE,                "OR_2"                  },
/* 158 */   { OP_SIZE,                "OR_4"                  },

/* 159 */   { OP_SIZE,                "XOR_BIT"               },
/* 160 */   { OP_SIZE,                "XOR_1"                 },
/* 161 */   { OP_SIZE,                "XOR_2"                 },
/* 162 */   { OP_SIZE,                "XOR_4"                 },

/* 163 */   { OP_SIZE,                "ADD_1"                 },
/* 164 */   { OP_SIZE,                "ADD_1_SGN"             },
/* 165 */   { OP_SIZE,                "ADD_2"                 },
/* 166 */   { OP_SIZE,                "ADD_2_SGN"             },
/* 167 */   { OP_SIZE,                "ADD_4"                 },
/* 168 */   { OP_SIZE,                "ADD_4_SGN"             },
/* 169 */   { OP_SIZE,                "ADD_FLOAT"             },

/* 170 */   { OP_SIZE,                "SUB_1"                 },
/* 171 */   { OP_SIZE,                "SUB_1_SGN"             },
/* 172 */   { OP_SIZE,                "SUB_2"                 },
/* 173 */   { OP_SIZE,                "SUB_2_SGN"             },
/* 174 */   { OP_SIZE,                "SUB_4"                 },
/* 175 */   { OP_SIZE,                "SUB_4_SGN"             },
/* 176 */   { OP_SIZE,                "SUB_FLOAT"             },

/* 177 */   { OP_SIZE,                "MUL_1"                 },
/* 178 */   { OP_SIZE,                "MUL_1_SGN"             },
/* 179 */   { OP_SIZE,                "MUL_2"                 },
/* 180 */   { OP_SIZE,                "MUL_2_SGN"             },
/* 181 */   { OP_SIZE,                "MUL_4"                 },
/* 182 */   { OP_SIZE,                "MUL_4_SGN"             },
/* 183 */   { OP_SIZE,                "MUL_FLOAT"             },

/* 184 */   { OP_SIZE,                "DIV_1"                 },
/* 185 */   { OP_SIZE,                "DIV_1_SGN"             },
/* 186 */   { OP_SIZE,                "DIV_2"                 },
/* 187 */   { OP_SIZE,                "DIV_2_SGN"             },
/* 188 */   { OP_SIZE,                "DIV_4"                 },
/* 189 */   { OP_SIZE,                "DIV_4_SGN"             },
/* 190 */   { OP_SIZE,                "DIV_FLOAT"             },
                                                           
/* 191 */   { OP_SIZE,                "GT_BIT"                },                                                            
/* 192 */   { OP_SIZE,                "GT_1"                  },
/* 193 */   { OP_SIZE,                "GT_1_SGN"              },
/* 194 */   { OP_SIZE,                "GT_2"                  },
/* 195 */   { OP_SIZE,                "GT_2_SGN"              },
/* 196 */   { OP_SIZE,                "GT_4"                  },
/* 197 */   { OP_SIZE,                "GT_4_SGN"              },
/* 198 */   { OP_SIZE,                "GT_FLOAT"              },
                                                              
/* 199 */   { OP_SIZE,                "GE_BIT"                },                                                              
/* 200 */   { OP_SIZE,                "GE_1"                  },
/* 201 */   { OP_SIZE,                "GE_1_SGN"              },
/* 202 */   { OP_SIZE,                "GE_2"                  },
/* 203 */   { OP_SIZE,                "GE_2_SGN"              },
/* 204 */   { OP_SIZE,                "GE_4"                  },
/* 205 */   { OP_SIZE,                "GE_4_SGN"              },
/* 206 */   { OP_SIZE,                "GE_FLOAT"              },
                                                             
/* 207 */   { OP_SIZE,                "LE_BIT"                },                                                             
/* 208 */   { OP_SIZE,                "LE_1"                  },
/* 209 */   { OP_SIZE,                "LE_1_SGN"              },
/* 210 */   { OP_SIZE,                "LE_2"                  },
/* 211 */   { OP_SIZE,                "LE_2_SGN"              },
/* 212 */   { OP_SIZE,                "LE_4"                  },
/* 213 */   { OP_SIZE,                "LE_4_SGN"              },
/* 214 */   { OP_SIZE,                "LE_FLOAT"              },
                                                              
/* 215 */   { OP_SIZE,                "LT_BIT"                },                                                              
/* 216 */   { OP_SIZE,                "LT_1"                  },
/* 217 */   { OP_SIZE,                "LT_1_SGN"              },
/* 218 */   { OP_SIZE,                "LT_2"                  },
/* 219 */   { OP_SIZE,                "LT_2_SGN"              },
/* 220 */   { OP_SIZE,                "LT_4"                  },
/* 221 */   { OP_SIZE,                "LT_4_SGN"              },
/* 222 */   { OP_SIZE,                "LT_FLOAT"              },

/* 223 */   { OP_SIZE,                "EQ_BIT"                },
/* 224 */   { OP_SIZE,                "EQ_1"                  },
/* 225 */   { OP_SIZE,                "EQ_2"                  },
/* 226 */   { OP_SIZE,                "EQ_4"                  },

/* 227 */   { OP_SIZE,                "NE_BIT"                },
/* 228 */   { OP_SIZE,                "NE_1"                  },
/* 229 */   { OP_SIZE,                "NE_2"                  },
/* 230 */   { OP_SIZE,                "NE_4"                  },
/* 231 */   { OP_PARBYTE_2,            "TYPECAST"              },
/* 232 */   { OP_SIZE,                "EQ_ANY"                },
/* 233 */   { OP_SIZE,                "NE_ANY"                },
/* 234 */   { OP_SIZE,                "GT_ANY"                },
/* 235 */   { OP_SIZE,                "SELCT_ARRAY_IND"        },
/* 236 */   { OP_SIZE,                "GE_ANY"                },
/* 237 */   { OP_SIZE,                "LT_ANY"                },
/* 238 */   { OP_SIZE,                "LE_ANY"                },
/* 239 */   { OP_PARBYTE_2,            "TRUNC"                    },

/* 240 */   { OP_PARBYTE_3,            "CREATE_BITREF_NEAR"    },  
/* 241 */   { OP_PARBYTE_5,            "CREATE_BITREF_FAR"        },  
/* 242 */   { OP_PARBYTE_3,            "CREATE_BITREF_BYREF"    },
/* 243 */   { OP_PARBYTE_1,            "CREATE_BITREF_IND"        },  

/* 244 */   { OP_NEAR_BYREF_SIZE,    "ST_STRING_NEAR"        },
/* 245 */   { OP_FAR_SIZE,            "ST_STRING_FAR"            },
/* 246 */   { OP_NEAR_BYREF_SIZE,    "ST_STRING_BYREF"        },
/* 247 */   { OP_SIZE,                "ST_STRING_IND"            }, 

/* 248 */   { OP_FAR_SIZE,            "CREATE_REF_FAR"        },  
/* 249 */   { OP_NEAR_BYREF_SIZE,    "CALCEN"                },
/* 250 */   { OP_SIZE,                ""                        },
/* 251 */   { OP_SIZE,                ""                        },
/* 252 */   { OP_SIZE,                ""                        },
/* 253 */   { OP_SIZE,                ""                        },
/* 254 */   { OP_SIZE,                "BREAK"                    },
/* 255 */   { OP_SIZE,                ""                        }
};


static tIpOpcodeStrTab IpExcodeStrTab[256] = {
/*   0 */    { OP_SIZE,                "EX_NOP"                },    
/*   1 */    { OP_SIZE,                "NOT_BIT"                },
/*   2 */    { OP_SIZE,                "NOT_1"                    },
/*   3 */    { OP_SIZE,                "NOT_2"                    },
/*   4 */    { OP_SIZE,                "NOT_4"                    },
/*   5 */    { OP_SIZE,                "SHL_1"                    },
/*   6 */    { OP_SIZE,                "SHL_2"                    },
/*   7 */    { OP_SIZE,                "SHL_4"                    },
/*   8 */    { OP_SIZE,                "SHR_1"                    },
/*   9 */    { OP_SIZE,                "SHR_2"                    },
/*  10 */    { OP_SIZE,                "SHR_4"                    }, 
/*  11 */    { OP_SIZE,                "ROL_1"                    },
/*  12 */    { OP_SIZE,                "ROL_2"                    },
/*  13 */    { OP_SIZE,                "ROL_4"                    },
/*  14 */    { OP_SIZE,                "ROR_1"                    },
/*  15 */    { OP_SIZE,                "ROR_2"                    },
/*  16 */    { OP_SIZE,                "ROR_4"                    },
/*  17 */    { OP_SIZE,                "ABS_1_SGN"                },   /* not supported by cbe & ip*/
/*  18 */    { OP_SIZE,                "ABS_2_SGN"                },
/*  19 */    { OP_SIZE,                "ABS_4_SGN"                },
/*  20 */    { OP_SIZE,                "ABS_FLOAT"                },
/*  21 */    { OP_SIZE,                "EXP"                    },      /* not supported by ip*/
/*  22 */    { OP_SIZE,                "SQRT"                    },
/*  23 */    { OP_SIZE,                "LN"                    },
/*  24 */    { OP_SIZE,                "LOG"                    },
/*  25 */    { OP_SIZE,                "SIN"                    },
/*  26 */    { OP_SIZE,                "COS"                    },
/*  27 */    { OP_SIZE,                "TAN"                    },
/*  28 */    { OP_SIZE,                "ASIN"                    },
/*  29 */    { OP_SIZE,                "ACOS"                    },
/*  30 */    { OP_SIZE,                "ATAN"                    },
/*  31 */    { OP_PARBYTE_3,        "CREATE_BITREF_DIR_BYREF"},
/*  32 */    { OP_SIZE,                "EXPT_1"                },     /* not supported by cbe & ip*/
/*  33 */    { OP_SIZE,                "EXPT_1_SGN"            },
/*  34 */    { OP_SIZE,                "EXPT_2"                },
/*  35 */    { OP_SIZE,                "EXPT_2_SGN"            },
/*  36 */    { OP_SIZE,                "EXPT_4"                }, 
/*  37 */    { OP_SIZE,                "EXPT_4_SGN"            },
/*  38 */    { OP_SIZE,                "EXPT_FLOAT"            }, 
/*  39 */    { OP_SIZE,                "MOD_1"                    }, /* not supported by cbe & ip*/
/*  40 */    { OP_SIZE,                "MOD_1_SGN"                },
/*  41 */    { OP_SIZE,                "MOD_2"                    },
/*  42 */    { OP_SIZE,                "MOD_2_SGN"                },
/*  43 */    { OP_SIZE,                "MOD_4"                    }, 
/*  44 */    { OP_SIZE,                "MOD_4_SGN"                },
/*  45 */    { OP_SIZE,                "MOD_FLOAT"                },
/*  46 */    { OP_SIZE,                "MOVE_1"                }, /* not supported by cbe & ip*/
/*  47 */    { OP_SIZE,                "MOVE_2"                },
/*  48 */    { OP_SIZE,                "MOVE_4"                },
/*  49 */    { OP_SIZE,                "MIN_1"                    }, /* not supported by cbe & ip*/
/*  50 */    { OP_SIZE,                "MIN_1_SGN"                },
/*  51 */    { OP_SIZE,                "MIN_2"                    },
/*  52 */    { OP_SIZE,                "MIN_2_SGN"                },
/*  53 */    { OP_SIZE,                "MIN_4"                    }, 
/*  54 */    { OP_SIZE,                "MIN_4_SGN"                },
/*  55 */    { OP_SIZE,                "MIN_FLOAT"                },
/*  56 */    { OP_SIZE,                "MAX_1"                    }, /* not supported by cbe & ip*/
/*  57 */    { OP_SIZE,                "MAX_1_SGN"                },
/*  58 */    { OP_SIZE,                "MAX_2"                    },
/*  59 */    { OP_SIZE,                "MAX_2_SGN"                },
/*  60 */    { OP_SIZE,                "MAX_4"                    }, 
/*  61 */    { OP_SIZE,                "MAX_4_SGN"                },
/*  62 */    { OP_SIZE,                "MAX_FLOAT"                },
/*  63 */    { OP_SIZE,                "LIMIT_1"                }, /* not supported by cbe & ip*/
/*  64 */    { OP_SIZE,                "LIMIT_1_SGN"            },
/*  65 */    { OP_SIZE,                "LIMIT_2"                },
/*  66 */    { OP_SIZE,                "LIMIT_2_SGN"            },
/*  67 */    { OP_SIZE,                "LIMIT_4"                }, 
/*  68 */    { OP_SIZE,                "LIMIT_4_SGN"            },
/*  69 */    { OP_SIZE,                "LIMIT_FLOAT"            },
/*  70 */    { OP_SIZE,                "LEN"                    },
/*  71 */    { OP_SIZE,                "LEFT"                    },
/*  72 */    { OP_SIZE,                "RIGHT"                    },
/*  73 */    { OP_SIZE,                "MID"                    },
/*  74 */    { OP_SIZE,                "CONCAT"                },
/*  75 */    { OP_SIZE,                "INSERT"                },
/*  76 */    { OP_SIZE,                "DELETE"                },
/*  77 */    { OP_SIZE,                "REPLACE"                },
/*  78 */    { OP_SIZE,                "FIND"                    },
/*  79 */    { OP_PARBYTE_2,        "EX_IO_WRITE"            },
/*  80 */    { OP_PARBYTE_2,        "EX_IO_READ"            }, 
/*  81 */    { OP_SIZE,                "MIN_ANY"                },
/*  82 */    { OP_SIZE,                "MAX_ANY"                },
/*  83 */    { OP_SIZE,                "SEL_BIT"                }, /* not supported by cbe & ip*/
/*  84 */    { OP_SIZE,                "SEL_1"                    },
/*  85 */    { OP_SIZE,                "SEL_2"                    },
/*  86 */    { OP_SIZE,                "SEL_4"                    }, 
/*  87 */    { OP_SIZE,                "SEL_ANY"                },
/*  88 */    { OP_SIZE,                "SEL_FLOAT"                },
/*  89 */    { OP_NEAR_BYREF_SIZE,    "ST_DIR_BYREF_STRING"    },    
/*  90 */    { OP_NEAR_BYREF_SIZE,    "LD_NEAR_8"                },    
/*  91 */    { OP_FAR_SIZE,            "LD_FAR_8"                },
/*  92 */    { OP_NEAR_BYREF_SIZE,    "LD_BYREF_8"            },    
/*  93 */    { OP_SIZE,                "LD_IND_8"                },      
/*  94 */    { OP_SIZE_CONST_8,        "LD_CONST_8"            },    
/*  95 */    { OP_NEAR_BYREF_SIZE,    "LDN_NEAR_8"            },          
/*  96 */    { OP_FAR_SIZE,            "LDN_FAR_8"                },     
/*  97 */    { OP_NEAR_BYREF_SIZE,    "LDN_BYREF_8"            },   
/*  98 */    { OP_SIZE,                "LDN_IND_8"                },     
/*  99 */    { OP_NEAR_BYREF_SIZE,    "LDS_NEAR_8"            },    
/* 100 */    { OP_FAR_SIZE,            "LDS_FAR_8"                },     
/* 101 */    { OP_NEAR_BYREF_SIZE,    "LDS_BYREF_8"            },   
/* 102 */    { OP_SIZE,                "LDS_IND_8"                },     
/* 103 */    { OP_SIZE_CONST_8,        "LDS_CONST_8"            },
/* 104 */    { OP_NEAR_BYREF_SIZE,    "LDNS_NEAR_8"            },   
/* 105 */    { OP_FAR_SIZE,            "LDNS_FAR_8"            },    
/* 106 */    { OP_NEAR_BYREF_SIZE,    "LDNS_BYREF_8"            },  
/* 107 */    { OP_SIZE,                "LDNS_IND_8"            },    
/* 108 */    { OP_NEAR_BYREF_SIZE,    "ST_NEAR_8"                },     
/* 109 */    { OP_FAR_SIZE,            "ST_FAR_8"                },      
/* 110 */    { OP_NEAR_BYREF_SIZE,    "ST_BYREF_8"            },    
/* 111 */    { OP_SIZE,                "ST_IND_8"                },      
/* 112 */    { OP_NEAR_BYREF_SIZE,    "STN_NEAR_8"            },    
/* 113 */    { OP_FAR_SIZE,            "STN_FAR_8"                },     
/* 114 */    { OP_NEAR_BYREF_SIZE,    "STN_BYREF_8"            },
/* 115 */    { OP_SIZE,                "STN_IND_8"                },     
/* 116 */    { OP_SIZE,                "PUSH_AE_8"                },         
/* 117 */    { OP_SIZE,                "POP_AE_8"                },          
/* 118 */    { OP_SIZE,                "AND_8"                    },        
/* 119 */    { OP_SIZE,                "OR_8"                    },        
/* 120 */    { OP_SIZE,                "XOR_8"                    },        
/* 121 */    { OP_SIZE,                "ADD_8"                    },        
/* 122 */    { OP_SIZE,                "ADD_8_SGN"                },        
/* 123 */    { OP_SIZE,                "ADD_DOUBLE"            },        
/* 124 */    { OP_SIZE,                "SUB_8"                    },        
/* 125 */    { OP_SIZE,                "SUB_8_SGN"                },        
/* 126 */    { OP_SIZE,                "SUB_DOUBLE"            },        
/* 127 */    { OP_SIZE,                "MUL_8"                    },        
/* 128 */    { OP_SIZE,                "MUL_8_SGN"                },        
/* 129 */    { OP_SIZE,                "MUL_DOUBLE"            },        
/* 130 */    { OP_SIZE,                "DIV_8"                    },        
/* 131 */    { OP_SIZE,                "DIV_8_SGN"                },        
/* 132 */    { OP_SIZE,                "DIV_DOUBLE"            },        
/* 133 */    { OP_SIZE,                "GT_8"                    },        
/* 134 */    { OP_SIZE,                "GT_8_SGN"                },        
/* 135 */    { OP_SIZE,                "GT_DOUBLE"                },         
/* 136 */    { OP_SIZE,                "GE_8"                    },        
/* 137 */    { OP_SIZE,                "GE_8_SGN"                },        
/* 138 */    { OP_SIZE,                "GE_DOUBLE"                },         
/* 139 */    { OP_SIZE,                "LE_8"                    },        
/* 140 */    { OP_SIZE,                "LE_8_SGN"                },        
/* 141 */    { OP_SIZE,                "LE_DOUBLE"                },         
/* 142 */    { OP_SIZE,                "LT_8"                    },        
/* 143 */    { OP_SIZE,                "LT_8_SGN"                },        
/* 144 */    { OP_SIZE,                "LT_DOUBLE"                },         
/* 145 */    { OP_SIZE,                "EQ_8"                    },              
/* 146 */    { OP_SIZE,                "NE_8"                    },              
/* 147 */    { OP_SIZE,                "NOT_8"                    },              
/* 148 */    { OP_SIZE,                "SHL_8"                    },
/* 149 */    { OP_SIZE,                "SHR_8"                    },
/* 148 */    { OP_SIZE,                "ROL_8"                    },
/* 149 */    { OP_SIZE,                "ROR_8"                    },
/* 152 */    { OP_SIZE,                "ABS_8"                    },        
/* 153 */    { OP_SIZE,                "ABS_8_SGN"                },        
/* 154 */    { OP_SIZE,                "ABS_DOUBLE"            },
/* 155 */    { OP_SIZE,                "MOD_8"                    },        
/* 156 */    { OP_SIZE,                "MOD_8_SGN"                },        
/* 157 */    { OP_SIZE,                "MOD_DOUBLE"            },          
/* 158 */    { OP_SIZE,                "EXPT_8"                },        
/* 159 */    { OP_SIZE,                "EXPT_8_SGN"            },        
/* 160 */    { OP_SIZE,                "EXPT_DOUBLE"            },        
/* 161 */    { OP_SIZE,                "MOVE_8"                },        
/* 162 */    { OP_SIZE,                "MIN_8"                    },        
/* 163 */    { OP_SIZE,                "MIN_8_SGN"                },        
/* 164 */    { OP_SIZE,                "MIN_DOUBLE"            },        
/* 165 */    { OP_SIZE,                "MAX_8"                    },        
/* 166 */    { OP_SIZE,                "MAX_8_SGN"                },        
/* 167 */    { OP_SIZE,                "MAX_DOUBLE"            },        
/* 168 */    { OP_SIZE,                "LIMIT_8"                },        
/* 169 */    { OP_SIZE,                "LIMIT_8_SGN"            },        
/* 170 */    { OP_SIZE,                "LIMIT_DOUBLE"            },        
/* 171 */    { OP_SIZE,                "SEL_8"                    },        
/* 172 */    { OP_SIZE,                "SEL_8_SGN"                },        
/* 173 */    { OP_SIZE,                "SEL_DOUBLE"            },        
/* 174 */    { OP_SIZE,                "EXP_DOUBLE"            },
/* 175 */    { OP_SIZE,                "SQRT_DOUBLE"            },
/* 176 */    { OP_SIZE,                "LN_DOUBLE"                },
/* 177 */    { OP_SIZE,                "LOG_DOUBLE"            },
/* 178 */    { OP_SIZE,                "SIN_DOUBLE"            },
/* 179 */    { OP_SIZE,                "COS_DOUBLE"            },
/* 180 */    { OP_SIZE,                "TAN_DOUBLE"            },
/* 181 */    { OP_SIZE,                "ASIN_DOUBLE"            },
/* 182 */    { OP_SIZE,                "ACOS_DOUBLE"            },
/* 183 */    { OP_SIZE,                "ATAN_DOUBLE"            },
/* 184 */    { OP_SIZE,                "NEG_BIT"                },
/* 185 */    { OP_SIZE,                "NEG_1"                    },
/* 186 */    { OP_SIZE,                "NEG_2"                    },
/* 187 */    { OP_SIZE,                "NEG_4"                    },
/* 188 */    { OP_SIZE,                "NEG_8"                    },
/* 189 */    { OP_SIZE,                "NEG_FLOAT"                },
/* 190 */    { OP_SIZE,                "NEG_DOUBLE"            },
/* 191 */    { OP_SIZE,                "ADD_DT"                },
/* 192 */    { OP_SIZE,                "SUB_DT_TIME"            },
/* 193 */    { OP_SIZE,                "SUB_DT_DT"                },
/* 194 */    { OP_SIZE,                "INPUT_PARA_C"            },
/* 195 */    { OP_SIZE,                "OUTPUT_PARA_C"            },
/* 196 */    { OP_SIZE,                "END_PARA"                },
/* 197 */    { OP_SIZE,                "EXPT_REAL48"            },
/* 198 */    { OP_NEAR_BYREF_SIZE,    "LD_DIR_BYREF_BIT"        },
/* 199 */    { OP_NEAR_BYREF_SIZE,    "LD_DIR_BYREF_1"        },
/* 200 */    { OP_NEAR_BYREF_SIZE,    "LD_DIR_BYREF_2"        },
/* 201 */    { OP_NEAR_BYREF_SIZE,    "LD_DIR_BYREF_4"        },
/* 202 */    { OP_NEAR_BYREF_SIZE,    "LD_DIR_BYREF_8"        },
/* 203 */    { OP_NEAR_BYREF_SIZE,    "LD_DIR_BYREF_ANY"        },
/* 204 */    { OP_NEAR_BYREF_SIZE,    "LDN_DIR_BYREF_BIT"        },
/* 205 */    { OP_NEAR_BYREF_SIZE,    "LDN_DIR_BYREF_1"        },
/* 206 */    { OP_NEAR_BYREF_SIZE,    "LDN_DIR_BYREF_2"        },
/* 207 */    { OP_NEAR_BYREF_SIZE,    "LDN_DIR_BYREF_4"        },
/* 208 */    { OP_NEAR_BYREF_SIZE,    "LDN_DIR_BYREF_8"        },
/* 209 */    { OP_NEAR_BYREF_SIZE,    "ST_DIR_BYREF_BIT"        },
/* 210 */    { OP_NEAR_BYREF_SIZE,    "ST_DIR_BYREF_1"        },
/* 211 */    { OP_NEAR_BYREF_SIZE,    "ST_DIR_BYREF_2"        },
/* 212 */    { OP_NEAR_BYREF_SIZE,    "ST_DIR_BYREF_4"        },
/* 213 */    { OP_NEAR_BYREF_SIZE,    "ST_DIR_BYREF_8"        },
/* 214 */    { OP_NEAR_BYREF_SIZE,    "ST_DIR_BYREF_ANY"        },
/* 215 */    { OP_NEAR_BYREF_SIZE,    "STN_DIR_BYREF_BIT"        },
/* 216 */    { OP_NEAR_BYREF_SIZE,    "STN_DIR_BYREF_1"        },
/* 217 */    { OP_NEAR_BYREF_SIZE,    "STN_DIR_BYREF_2"        },
/* 218 */    { OP_NEAR_BYREF_SIZE,    "STN_DIR_BYREF_4"        },
/* 219 */    { OP_NEAR_BYREF_SIZE,    "STN_DIR_BYREF_8"        },
/* 220 */    { OP_SIZE,                "EXPT_DOUBLE_1_SGN"        },
/* 221 */    { OP_SIZE,                "EXPT_DOUBLE_1"            },
/* 222 */    { OP_SIZE,                "EXPT_DOUBLE_2_SGN"        },    
/* 223 */    { OP_SIZE,                "EXPT_DOUBLE_2"            },
/* 224 */    { OP_SIZE,                "EXPT_DOUBLE_3_SGN"        },
/* 225 */    { OP_SIZE,                "EXPT_DOUBLE_3"            },       
/* 226 */    { OP_SIZE,                "EXPT_DOUBLE_4_SGN"        },
/* 227 */    { OP_SIZE,                "EXPT_DOUBLE_4"            },
/* 228 */    { OP_SIZE,                "EXPT_DOUBLE_8_SGN"        },    
/* 229 */    { OP_SIZE,                "EXPT_DOUBLE_8"            },
/* 230 */    { OP_SIZE,                "EXPT_DOUBLE_FLOAT"        },      
/* 231 */    { OP_SIZE,                "EXPT_DOUBLE_REAL48"    },        
/* 232 */    { OP_SIZE,                "EXPT_DOUBLE_DOUBLE"    },    
/* 233 */    { OP_NEAR_BYREF_SIZE,    "S_DIR_BYREF_BIT"        },    
/* 234 */    { OP_NEAR_BYREF_SIZE,    "R_DIR_BYREF_BIT"        },    
/* 235 */    { OP_NEAR_BYREF_SIZE,    "LDS_DIR_BYREF_BIT"        },    
/* 236 */    { OP_NEAR_BYREF_SIZE,    "LDS_DIR_BYREF_1"        },    
/* 237 */    { OP_NEAR_BYREF_SIZE,    "LDS_DIR_BYREF_2"        },    
/* 238 */    { OP_NEAR_BYREF_SIZE,    "LDS_DIR_BYREF_4"        },    
/* 239 */    { OP_NEAR_BYREF_SIZE,    "LDS_DIR_BYREF_8"        },    
/* 240 */    { OP_NEAR_BYREF_SIZE,    "LDS_DIR_BYREF_ANY"        },    
/* 241 */    { OP_NEAR_BYREF_SIZE,    "LDNS_DIR_BYREF_BIT"    },    
/* 242 */    { OP_NEAR_BYREF_SIZE,    "LDNS_DIR_BYREF_1"        },    
/* 243 */    { OP_NEAR_BYREF_SIZE,    "LDNS_DIR_BYREF_2"        },    
/* 244 */    { OP_NEAR_BYREF_SIZE,    "LDNS_DIR_BYREF_4"        },    
/* 245 */    { OP_NEAR_BYREF_SIZE,    "LDNS_DIR_BYREF_8"        },    
/* 246 */    { OP_NEAR_BYREF_SIZE,    "CREATE_DIR_REFERENCE"    },    
/* 247 */    { OP_FAR_SIZE,            "CREATE_DIR_REFERENCE_FAR"},    
/* 248 */    { OP_NEAR_BYREF_SIZE,    "LD_DIR_REFERENCE"        },    
/* 249 */    { OP_FAR_SIZE,            "ST_DIR_REFERENCE"        },
/* 250 */    { OP_SIZE,             "ADD_TOD_TIME"          },    
/* 251 */    { OP_SIZE,                "SUB_DATE_DATE"         },    
/* 252 */    { OP_SIZE,             "SUB_TOD_TIME"          },    
/* 253 */    { OP_SIZE,             "SUB_TOD_TOD"           },    
/* 254 */    { OP_SIZE,             ""                      },    
/* 255 */    { OP_SIZE,                ""                        }
};

static tIpOpcodeStrTab IpEx2codeStrTab[256] = {
/*   0 */    { OP_SIZE,                "EX2_NOP"                },    
/*   1 */    { OP_SIZE_CONST_6,     "LDA_NEAR"              },
/*   2 */    { OP_SIZE_CONST_6,     "LDA_BYREF"             },
/*   3 */    { OP_SIZE_CONST_8,     "LDA_FAR"               },
/*   4 */    { OP_SIZE_CONST_6,     "LDAS_NEAR"             },
/*   5 */    { OP_SIZE_CONST_6,     "LDAS_BYREF"            },
/*   6 */    { OP_SIZE_CONST_8,     "LDAS_FAR"              },
/*   7 */    { OP_SIZE,                ""                        },    
/*   8 */    { OP_SIZE,                ""                        },    
/*   9 */    { OP_SIZE,                ""                        },    
/*  10 */    { OP_NEAR_BYREF_SIZE,    "LD_NEAR_6"                },    
/*  11 */    { OP_FAR_SIZE,            "LD_FAR_6"                },
/*  12 */    { OP_NEAR_BYREF_SIZE,    "LD_BYREF_6"            },    
/*  13 */    { OP_SIZE,                "LD_IND_6"                },      
/*  14 */    { OP_SIZE_CONST_6,        "LD_CONST_6"            },    
/*  15 */    { OP_NEAR_BYREF_SIZE,    "LDN_NEAR_6"            },          
/*  16 */    { OP_FAR_SIZE,            "LDN_FAR_6"                },     
/*  17 */    { OP_NEAR_BYREF_SIZE,    "LDN_BYREF_6"            },   
/*  18 */    { OP_SIZE,                "LDN_IND_6"                },     
/*  19 */    { OP_NEAR_BYREF_SIZE,    "LDS_NEAR_6"            },    
/*  20 */    { OP_FAR_SIZE,            "LDS_FAR_6"                },     
/*  21 */    { OP_NEAR_BYREF_SIZE,    "LDS_BYREF_6"            },   
/*  22 */    { OP_SIZE,                "LDS_IND_6"                },     
/*  23 */    { OP_SIZE_CONST_6,        "LDS_CONST_6"            },
/*  24 */    { OP_NEAR_BYREF_SIZE,    "LDNS_NEAR_6"            },   
/*  25 */    { OP_FAR_SIZE,            "LDNS_FAR_6"            },    
/*  26 */    { OP_NEAR_BYREF_SIZE,    "LDNS_BYREF_6"            },  
/*  27 */    { OP_SIZE,                "LDNS_IND_6"            },    
/*  28 */    { OP_NEAR_BYREF_SIZE,    "ST_NEAR_6"                },     
/*  29 */    { OP_FAR_SIZE,            "ST_FAR_6"                },      
/*  30 */    { OP_NEAR_BYREF_SIZE,    "ST_BYREF_6"            },    
/*  31 */    { OP_SIZE,                "ST_IND_6"                },      
/*  32 */    { OP_NEAR_BYREF_SIZE,    "STN_NEAR_6"            },    
/*  33 */    { OP_FAR_SIZE,            "STN_FAR_6"                },     
/*  34 */    { OP_NEAR_BYREF_SIZE,    "STN_BYREF_6"            },
/*  35 */    { OP_SIZE,                "STN_IND_6"                },     
/*  36 */    { OP_SIZE,                "PUSH_AE_6"                },         
/*  37 */    { OP_SIZE,                "POP_AE_6"                },          
/*  38 */    { OP_SIZE,                "AND_6"                    },        
/*  39 */    { OP_SIZE,                "OR_6"                    },        
/*  40 */    { OP_SIZE,                "XOR_6"                    },        
/*  41 */    { OP_SIZE,                "ADD_6"                    },
/*  42 */    { OP_SIZE,                "ADD_6_SGN"                },
/*  43 */    { OP_SIZE,                "ADD_REAL48"            },        
/*  44 */    { OP_SIZE,                "SUB_6"                    },
/*  45 */    { OP_SIZE,                "SUB_6_SGN"                },
/*  46 */    { OP_SIZE,                "SUB_REAL48"            },             
/*  47 */    { OP_SIZE,                "MUL_6"                    },
/*  48 */    { OP_SIZE,                "MUL_6_SGN"                },
/*  49 */    { OP_SIZE,                "MUL_REAL48"            },        
/*  50 */    { OP_SIZE,                "DIV_6"                    },
/*  51 */    { OP_SIZE,                "DIV_6_SGN"                },
/*  52 */    { OP_SIZE,                "DIV_REAL48"            },        
/*  53 */    { OP_SIZE,                "GT_6"                    },
/*  54 */    { OP_SIZE,                "GT_6_SGN"                },
/*  55 */    { OP_SIZE,                "GT_REAL48"                },         
/*  56 */    { OP_SIZE,                "GE_6"                    },
/*  57 */    { OP_SIZE,                "GE_6_SGN"                },
/*  58 */    { OP_SIZE,                "GE_REAL48"                },         
/*  59 */    { OP_SIZE,                "LE_6"                    },
/*  60 */    { OP_SIZE,                "LE_6_SGN"                },
/*  61 */    { OP_SIZE,                "LE_REAL48"                },         
/*  62 */    { OP_SIZE,                "LT_6"                    },
/*  63 */    { OP_SIZE,                "LT_6_SGN"                },
/*  64 */    { OP_SIZE,                "LT_REAL48"                },         
/*  65 */    { OP_SIZE,                "EQ_6"                    },              
/*  66 */    { OP_SIZE,                "NE_6"                    },              
/*  67 */    { OP_SIZE,                "NOT_6"                    },
/*  68 */    { OP_SIZE,                "SHL_6"                    },
/*  69 */    { OP_SIZE,                "SHR_6"                    },
/*  70 */    { OP_SIZE,                "ROL_6"                    },
/*  71 */    { OP_SIZE,                "ROR_6"                    },
/*  72 */    { OP_SIZE,                "ABS_6"                    },
/*  73 */    { OP_SIZE,                "ABS_6_SGN"                },
/*  74 */    { OP_SIZE,                "ABS_REAL48"            },
/*  75 */    { OP_SIZE,                "MOD_6"                    },
/*  76 */    { OP_SIZE,                "MOD_6_SGN"                },
/*  77 */    { OP_SIZE,                "MOD_REAL48"            },
/*  78 */    { OP_SIZE,                ""                        },
/*  79 */    { OP_SIZE,                ""                        },
/*  80 */    { OP_SIZE,                "EXPT_3"                }, /* not supported by cbe & ip*/
/*  81 */    { OP_SIZE,                "EXPT_3_SGN"            },
/*  82 */    { OP_SIZE,                "EXPT_6"                },
/*  83 */    { OP_SIZE,                "EXPT_6_SGN"            },
/*  84 */    { OP_SIZE,                "EXPT_REAL48_1_SGN"        },
/*  85 */    { OP_SIZE,                "EXPT_REAL48_1"            }, /* not supported by cbe & ip*/
/*  86 */    { OP_SIZE,                "EXPT_REAL48_2_SGN"        },
/*  87 */    { OP_SIZE,                "EXPT_REAL48_2"            },
/*  88 */    { OP_SIZE,                "EXPT_REAL48_3_SGN"        },
/*  89 */    { OP_SIZE,                "EXPT_REAL48_3"            },
/*  90 */    { OP_SIZE,                "EXPT_REAL48_4_SGN"        },
/*  91 */    { OP_SIZE,                "EXPT_REAL48_4"            }, /* not supported by cbe & ip*/
/*  92 */    { OP_SIZE,                "EXPT_REAL48_8_SGN"        },
/*  93 */    { OP_SIZE,                "EXPT_REAL48_8"            },
/*  94 */    { OP_SIZE,                "EXPT_REAL48_FLOAT"        },
/*  95 */    { OP_SIZE,                "EXPT_REAL48_REAL48"    },
/*  96 */    { OP_SIZE,                "EXPT_REAL48_DOUBLE"    },    
/*  97 */    { OP_SIZE,                ""                        },
/*  98 */    { OP_SIZE,                ""                        },
/*  99 */    { OP_SIZE,                ""                        },
/* 100 */    { OP_SIZE,                "MIN_6"                    },
/* 101 */    { OP_SIZE,                "MIN_6_SGN"                },
/* 102 */    { OP_SIZE,                "MIN_REAL48"            },
/* 103 */    { OP_SIZE,                "MAX_6"                    },
/* 104 */    { OP_SIZE,                "MAX_6_SGN"                },
/* 105 */    { OP_SIZE,                "MAX_REAL48"            },
/* 106 */    { OP_SIZE,                "LIMIT_6"                },
/* 107 */    { OP_SIZE,                "LIMIT_6_SGN"            },
/* 108 */    { OP_SIZE,                "LIMIT_REAL48"            },
/* 109 */    { OP_SIZE,                "SEL_6"                    },
/* 110 */    { OP_SIZE,                "SEL_6_SGN"                },
/* 111 */    { OP_SIZE,                "SEL_REAL48"            },
/* 112 */    { OP_SIZE,                ""                        },
/* 113 */    { OP_SIZE,                ""                        },
/* 114 */    { OP_SIZE,                ""                        },
/* 115 */    { OP_SIZE,                ""                        },
/* 116 */    { OP_SIZE,                ""                        },
/* 117 */    { OP_SIZE,                ""                        },
/* 118 */    { OP_SIZE,                ""                        },
/* 119 */    { OP_SIZE,                ""                        },
/* 120 */    { OP_SIZE,                ""                        },
/* 121 */    { OP_SIZE,                ""                        },
/* 122 */    { OP_SIZE,                "NEG_REAL48"            },
/* 123 */    { OP_SIZE,                "NEG_6"                    },
/* 124 */    { OP_SIZE,                ""                        },
/* 125 */    { OP_SIZE,                ""                        },
/* 126 */    { OP_SIZE,                ""                        },
/* 127 */    { OP_SIZE,                ""                        },
/* 128 */    { OP_SIZE,                ""                        },
/* 129 */    { OP_SIZE,                ""                        },
/* 130 */    { OP_SIZE,                ""                        },
/* 131 */    { OP_SIZE,                ""                        },
/* 132 */    { OP_SIZE,                ""                        },
/* 133 */    { OP_SIZE,                ""                        },
/* 134 */    { OP_SIZE,                ""                        },
/* 135 */    { OP_SIZE,                ""                        },
/* 136 */    { OP_SIZE,                ""                        },
/* 137 */    { OP_SIZE,                ""                        },
/* 138 */    { OP_SIZE,                ""                        },
/* 139 */    { OP_SIZE,                ""                        },
/* 140 */    { OP_SIZE,                ""                        },
/* 141 */    { OP_SIZE,                ""                        },
/* 142 */    { OP_SIZE,                ""                        },
/* 143 */    { OP_SIZE,                ""                        },
/* 144 */    { OP_SIZE,                ""                        },
/* 145 */    { OP_SIZE,                ""                        },
/* 146 */    { OP_SIZE,                ""                        },
/* 147 */    { OP_SIZE,                ""                        },
/* 148 */    { OP_SIZE,                ""                        },
/* 149 */    { OP_SIZE,                ""                        },
/* 150 */    { OP_NEAR_BYREF_SIZE,    "LD_NEAR_3"                },    
/* 151 */    { OP_FAR_SIZE,            "LD_FAR_3"                },
/* 152 */    { OP_NEAR_BYREF_SIZE,    "LD_BYREF_3"            },    
/* 153 */    { OP_SIZE,                "LD_IND_3"                },      
/* 154 */    { OP_SIZE_CONST_3,        "LD_CONST_3"            },    
/* 155 */    { OP_NEAR_BYREF_SIZE,    "LDN_NEAR_3"            },          
/* 156 */    { OP_FAR_SIZE,            "LDN_FAR_3"                },     
/* 157 */    { OP_NEAR_BYREF_SIZE,    "LDN_BYREF_3"            },   
/* 158 */    { OP_SIZE,                "LDN_IND_3"                },     
/* 159 */    { OP_NEAR_BYREF_SIZE,    "LDS_NEAR_3"            },    
/* 160 */    { OP_FAR_SIZE,            "LDS_FAR_3"                },     
/* 161 */    { OP_NEAR_BYREF_SIZE,    "LDS_BYREF_3"            },   
/* 162 */    { OP_SIZE,                "LDS_IND_3"                },     
/* 163 */    { OP_SIZE_CONST_3,        "LDS_CONST_3"            },
/* 164 */    { OP_NEAR_BYREF_SIZE,    "LDNS_NEAR_3"            },   
/* 165 */    { OP_FAR_SIZE,            "LDNS_FAR_3"            },    
/* 166 */    { OP_NEAR_BYREF_SIZE,    "LDNS_BYREF_3"            },  
/* 167 */    { OP_SIZE,                "LDNS_IND_3"            },    
/* 168 */    { OP_NEAR_BYREF_SIZE,    "ST_NEAR_3"                },     
/* 169 */    { OP_FAR_SIZE,            "ST_FAR_3"                },      
/* 170 */    { OP_NEAR_BYREF_SIZE,    "ST_BYREF_3"            },    
/* 171 */    { OP_SIZE,                "ST_IND_3"                },      
/* 172 */    { OP_NEAR_BYREF_SIZE,    "STN_NEAR_3"            },    
/* 173 */    { OP_FAR_SIZE,            "STN_FAR_3"                },     
/* 174 */    { OP_NEAR_BYREF_SIZE,    "STN_BYREF_3"            },
/* 175 */    { OP_SIZE,                "STN_IND_3"                },     
/* 176 */    { OP_SIZE,                "PUSH_AE_3"                },         
/* 177 */    { OP_SIZE,                "POP_AE_3"                },          
/* 178 */    { OP_SIZE,                "AND_3"                    },        
/* 179 */    { OP_SIZE,                "OR_3"                    },        
/* 180 */    { OP_SIZE,                "XOR_3"                    },        
/* 181 */    { OP_SIZE,                "ADD_3"                    },
/* 182 */    { OP_SIZE,                "ADD_3_SGN"                },
/* 183 */    { OP_SIZE,                "SUB_3"                    },
/* 184 */    { OP_SIZE,                "SUB_3_SGN"                },
/* 185 */    { OP_SIZE,                "MUL_3"                    },
/* 186 */    { OP_SIZE,                "MUL_3_SGN"                },
/* 187 */    { OP_SIZE,                "DIV_3"                    },
/* 188 */    { OP_SIZE,                "DIV_3_SGN"                },
/* 189 */    { OP_SIZE,                "GT_3"                    },
/* 190 */    { OP_SIZE,                "GT_3_SGN"                },
/* 191 */    { OP_SIZE,                "GE_3"                    },
/* 192 */    { OP_SIZE,                "GE_3_SGN"                },
/* 193 */    { OP_SIZE,                "LE_3"                    },
/* 194 */    { OP_SIZE,                "LE_3_SGN"                },
/* 195 */    { OP_SIZE,                "LT_3"                    },
/* 196 */    { OP_SIZE,                "LT_3_SGN"                },
/* 197 */    { OP_SIZE,                "EQ_3"                    },              
/* 198 */    { OP_SIZE,                "NE_3"                    },              
/* 199 */    { OP_SIZE,                "NOT_3"                    },
/* 200 */    { OP_SIZE,                "SHL_3"                    },
/* 201 */    { OP_SIZE,                "SHR_3"                    },
/* 202 */    { OP_SIZE,                "ROL_3"                    },
/* 203 */    { OP_SIZE,                "ROR_3"                    },
/* 204 */    { OP_SIZE,                "ABS_3"                    },
/* 205 */    { OP_SIZE,                "ABS_3_SGN"                },  
/* 206 */    { OP_SIZE,                "MOD_3"                    }, 
/* 207 */    { OP_SIZE,                "MOD_3_SGN"                },
/* 208 */    { OP_SIZE,                ""                        },
/* 209 */    { OP_SIZE,                ""                        },
/* 210 */    { OP_SIZE,                ""                        },
/* 211 */    { OP_SIZE,                ""                        },
/* 212 */    { OP_SIZE,                "MIN_3"                    }, 
/* 213 */    { OP_SIZE,                "MIN_3_SGN"                },
/* 214 */    { OP_SIZE,                "MAX_3"                    }, 
/* 215 */    { OP_SIZE,                "MAX_3_SGN"                },
/* 216 */    { OP_SIZE,                ""                        },
/* 217 */    { OP_SIZE,                ""                        },
/* 218 */    { OP_SIZE,                ""                        },
/* 219 */    { OP_SIZE,                ""                        },
/* 220 */    { OP_SIZE,                ""                        },
/* 221 */    { OP_SIZE,                ""                        },
/* 222 */    { OP_SIZE,                "NEG_3"                    },
/* 223 */    { OP_NEAR_BYREF_SIZE,    "LD_DIR_BYREF_6"        },
/* 224 */    { OP_NEAR_BYREF_SIZE,    "LDN_DIR_BYREF_6"        },
/* 225 */    { OP_NEAR_BYREF_SIZE,    "LDS_DIR_BYREF_6"        },
/* 226 */    { OP_NEAR_BYREF_SIZE,    "LDNS_DIR_BYREF_6"        },
/* 227 */    { OP_NEAR_BYREF_SIZE,    "ST_DIR_BYREF_6"        },
/* 228 */    { OP_NEAR_BYREF_SIZE,    "STN_DIR_BYREF_6"        },
/* 229 */    { OP_NEAR_BYREF_SIZE,    "LD_DIR_BYREF_3"        },
/* 230 */    { OP_NEAR_BYREF_SIZE,    "LDN_DIR_BYREF_3"        },    
/* 231 */    { OP_NEAR_BYREF_SIZE,    "LDS_DIR_BYREF_3"        },
/* 232 */    { OP_NEAR_BYREF_SIZE,    "LDNS_DIR_BYREF_3"        },
/* 233 */    { OP_NEAR_BYREF_SIZE,    "ST_DIR_BYREF_3"        },
/* 234 */    { OP_NEAR_BYREF_SIZE,    "STN_DIR_BYREF_3"        },
/* 235 */    { OP_NEAR_BYREF_SIZE,    "ST_NEAR_WSTRING"        },
/* 236 */    { OP_FAR_SIZE,            "ST_FAR_WSTRING"        },
/* 237 */    { OP_SIZE,                "ST_BYREF_WSTRING"        },
/* 238 */    { OP_NEAR_BYREF_SIZE,    "ST_IND_WSTRING"        },
/* 239 */    { OP_NEAR_BYREF_SIZE,    "ST_DIR_BYREF_WSTRING"    },
/* 240 */    { OP_NEAR_BYREF_SIZE,    "ST_NEAR_ARRAY"            },
/* 241 */    { OP_FAR_SIZE,            "ST_FAR_ARRAY"            },
/* 242 */    { OP_NEAR_BYREF_SIZE,    "ST_BYREF_ARRAY"        },
/* 243 */    { OP_SIZE,                "ST_IND_ARRAY"            },
/* 244 */    { OP_NEAR_BYREF_SIZE,    "ST_DIR_BYREF_ARRAY"    },
/* 245 */    { OP_SIZE,                ""                        },
/* 246 */    { OP_SIZE,                ""                        },
/* 247 */    { OP_SIZE,                ""                        },
/* 248 */    { OP_SIZE,                ""                        },
/* 249 */    { OP_SIZE,                ""                        },
/* 250 */    { OP_SIZE,                ""                        },
/* 251 */    { OP_SIZE,                ""                        },
/* 252 */    { OP_SIZE,                ""                        },
/* 253 */    { OP_SIZE,                ""                        },
/* 254 */    { OP_SIZE,                ""                        },
/* 255 */    { OP_SIZE,                ""                        }
};



#endif /* AFX_IPDISTBL_H__71B277FD_5B3B_11D5_9CFF_009027715570__INCLUDED_*/
